name: Security Build
on:  # yamllint disable-line rule:truthy
  push:
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true
      SNYK_ORG:
        required: true
  workflow_dispatch: {}

jobs:
  snyk:
    name: Snyk
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Source
        uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --org=${{ secrets.SNYK_ORG }} --severity-threshold=medium

  snyk-code:
    name: Snyk Code
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Source
        uses: actions/checkout@master
      - name: Run Snyk SAST to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --org=${{ secrets.SNYK_ORG }}
          command: code test
